version: '2.6'
services:
  api:
    container_name: "follow-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: followers-db
      DB_HOST: follow_db
      DB_PORT: 5432
      DD_API_KEY: ${DD_API_KEY}

  db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  datadog:
    image: datadog/agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro


volumes:
  pgdata:
    external: false
