version: '2.6'
services:
  api:
    container_name: "follow-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: followers-db
      DB_HOST: db
      DB_PORT: 5433

  db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: followers-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
